#!/usr/bin/env python3
"""Report broad Fortran `use module` imports without `only:` lists."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import check_fortran_interface_hygiene as hygiene
from repo_paths import ROOT, repo_path


REPORT_PATH = repo_path("docs", "fortran_broad_import_audit.md")


@dataclass(frozen=True)
class BroadImport:
    path: Path
    line: int
    scope: str
    module: str


@dataclass(frozen=True)
class ImportClassification:
    category: str
    action: str


def classify_broad_import(row: BroadImport) -> ImportClassification:
    """Explain why a remaining broad import is still broad."""

    rel = row.path.relative_to(ROOT).as_posix()
    module = row.module

    if module == "mpi":
        return ImportClassification(
            "MPI compiler interface",
            "Keep broad unless a guarded `only:` list is validated on Derecho.",
        )
    if module == "cgns":
        return ImportClassification(
            "optional CGNS interface",
            "Keep broad unless the PPCGNS build profile is validated.",
        )
    if (
        rel.startswith("level_set")
        or rel.startswith("trees_")
        or module in {"level_set_base", "trees_base_ls"}
    ):
        return ImportClassification(
            "LVLSET deferred",
            "Leave for a separate LVLSET cleanup/validation pass.",
        )
    if rel.startswith("level_set") and module in {"grid_m", "messages", "sim_param"}:
        return ImportClassification(
            "LVLSET deferred",
            "Leave for a separate LVLSET cleanup/validation pass.",
        )
    return ImportClassification(
        "candidate",
        "Review for a narrow `only:` list before changing source.",
    )


def current_scope(line: str, stack: list[str]) -> list[str]:
    lower = line.lower()
    module_match = re.match(r"^module\s+(?!procedure\b)(\w+)", lower)
    if module_match:
        return [module_match.group(1)]
    if re.match(r"^end\s+module\b", lower):
        return []

    procedure_match = re.match(
        r"^(?:(?:recursive|pure|elemental|impure)\s+)*"
        r"(?:(?:integer|real|logical|complex|character|type|class)"
        r"\s*(?:\([^)]*\))?\s+)?(subroutine|function)\s+(\w+)",
        lower,
    )
    if procedure_match:
        return [*stack, procedure_match.group(2)]
    if re.match(r"^end\s+(subroutine|function)\b", lower) and len(stack) > 1:
        return stack[:-1]
    return stack


def collect_broad_imports(paths: list[Path]) -> list[BroadImport]:
    rows: list[BroadImport] = []
    use_re = re.compile(
        r"^use\s*(?:,\s*[^:]+::\s*)?(\w+)(?:\s*,\s*only\s*:\s*(.+))?$",
        flags=re.I,
    )

    for path in paths:
        scope: list[str] = []
        for line_no, line in hygiene.logical_lines(path):
            scope = current_scope(line, scope)
            match = use_re.match(line)
            if not match or match.group(2) is not None:
                continue
            rows.append(
                BroadImport(
                    path=path,
                    line=line_no,
                    scope="::".join(scope) if scope else "(file scope)",
                    module=match.group(1).lower(),
                )
            )
    return rows


def markdown_report(rows: list[BroadImport]) -> str:
    by_file = Counter(row.path.relative_to(ROOT).as_posix() for row in rows)
    by_category = Counter(classify_broad_import(row).category for row in rows)
    lines = [
        "# Fortran Broad Import Audit",
        "",
        "Generated by `python3 tools/report_fortran_broad_imports.py --write`.",
        "",
        "This is a readability map, not a failure list.  Broad imports from",
        "`mpi`, `openacc`, `cufft`, `cgns`, and old LESGO shared modules can be",
        "reasonable when the call site is tightly coupled to that module.  Use",
        "this report to choose small, reviewable import cleanups instead of",
        "rewriting large solver files in one pass.",
        "",
        "The `category` and `recommended action` columns distinguish safe",
        "cleanup candidates from intentionally broad imports that depend on",
        "external compiler interfaces or deferred optional modules.",
        "",
        f"Total broad imports: `{len(rows)}`",
        "",
        "## Category Summary",
        "",
        "| Category | Broad imports |",
        "| --- | ---: |",
    ]

    for category, count in by_category.most_common():
        lines.append(f"| {category} | {count} |")

    lines.extend(
        [
            "",
            "## Highest-Count Files",
            "",
            "| File | Broad imports |",
            "| --- | ---: |",
        ]
    )

    for path, count in by_file.most_common(20):
        lines.append(f"| `{path}` | {count} |")

    lines.extend(
        [
            "",
            "## Full List",
            "",
            "| File | Line | Scope | Module | Category | Recommended action |",
            "| --- | ---: | --- | --- | --- | --- |",
        ]
    )

    for row in rows:
        rel = row.path.relative_to(ROOT).as_posix()
        classification = classify_broad_import(row)
        lines.append(
            f"| `{rel}` | {row.line} | `{row.scope}` | `{row.module}` | "
            f"{classification.category} | {classification.action} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Report tracked Fortran broad imports that omit `only:` lists."
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"write the Markdown report to {REPORT_PATH.relative_to(ROOT)}",
    )
    args = parser.parse_args()

    rows = collect_broad_imports(hygiene.tracked_fortran_files())
    report = markdown_report(rows)
    if args.write:
        REPORT_PATH.write_text(report, encoding="utf-8")
    else:
        print(report, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
